name: Building From Sources

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

concurrency: production

jobs:
  docker-build:
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get lowercase repository name
        run: |
          echo "GH_LWREPONAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ env.GH_LWREPONAME }}:1.1-${{ github.run_number }}
          cache-from: type=gha